projeto.pedido/Controllers/ClientController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using projeto.pedido.Controllers.Base;
using projeto.pedido.DbContext;
using projeto.pedido.Models.Entities;
using projeto.pedido.Models.View.Base;
using projeto.pedido.Repository;
using projeto.pedido.Repository.Base;

namespace projeto.pedido.Controllers
{
    public class ClientController : BaseController<BaseViewModel<ClientEntity>, ClientRepository, ClientEntity>
    {
        public ClientController(ClientRepository repository) : base(repository)
        {
        }

//        protected override List<ClientEntity> Sort(List<ClientEntity> list, string sortColumn, bool isAsc)
//        {
//            //SORTING
//            if (!string.IsNullOrEmpty(sortColumn))
//            {
//                switch (sortColumn)
//                {
//                    case "Id":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Id).ToList()
//                            : list.OrderByDescending(s => s.Id).ToList();
//                        break;
//                    case "Name":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Name).ToList()
//                            : list.OrderByDescending(s => s.Name).ToList();
//                        break;
//
//                    case "Phone":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Phone).ToList()
//                            : list.OrderByDescending(s => s.Phone).ToList();
//                        break;
//                }
//            }
//
//            return list;
//        }
    }
}

projeto.pedido/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using projeto.pedido.Controllers.Base;
using projeto.pedido.Models;
using projeto.pedido.Models.Entities;
using projeto.pedido.Models.View;
using projeto.pedido.Repository;

namespace projeto.pedido.Controllers
{
    public class OrderController : BaseController<OrderViewModel, OrderRepository, OrderEntity>
    {
        private readonly ProductRepository _productRepository;
        private readonly ClientRepository _clientRepository;

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        public OrderController(OrderRepository repository, ProductRepository productRepository,
            ClientRepository clientRepository) : base(repository)
        {
            _productRepository = productRepository;
            _clientRepository = clientRepository;
        }

        protected override async Task CompletViewModel(OrderViewModel viewModel)
        {
            viewModel.ProductList = await _productRepository.GetAll();
            viewModel.ClientList = await _clientRepository.GetAll();
        }

        protected override async Task GetIncludes(OrderEntity entity)
        {
            entity.Product = await _productRepository.GetAsync(entity.ProductId);
            entity.Client = await _clientRepository.GetAsync(entity.ClientId);
        }

//        protected override List<OrderEntity> Sort(List<OrderEntity> list, string sortColumn, bool isAsc)
//        {
//            //SORTING
//            if (!string.IsNullOrEmpty(sortColumn))
//            {
//                switch (sortColumn)
//                {
//                    case "Id":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Id).ToList()
//                            : list.OrderByDescending(s => s.Id).ToList();
//                        break;
//                    case "Client.Name":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Client.Name).ToList()
//                            : list.OrderByDescending(s => s.Client.Name).ToList();
//                        break;
//
//                    case "Product.Name":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Product.Name).ToList()
//                            : list.OrderByDescending(s => s.Product.Name).ToList();
//                        break;
//
//                    case "Total":
//                        list = isAsc
//                            ? list.OrderBy(s => s.TotalValue).ToList()
//                            : list.OrderByDescending(s => s.TotalValue).ToList();
//                        break;
//                }
//            }
//
//            return list;
//        }
    }
}

projeto.pedido/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using projeto.pedido.Controllers.Base;
using projeto.pedido.Models.Entities;
using projeto.pedido.Models.View.Base;
using projeto.pedido.Repository;

namespace projeto.pedido.Controllers
{
    public class ProductController : BaseController<BaseViewModel<ProductEntity>, ProductRepository, ProductEntity>
    {
        public ProductController(ProductRepository repository) : base(repository)
        {
        }

//        protected override List<ProductEntity> Sort(List<ProductEntity> list, string sortColumn, bool isAsc)
//        {
//            //SORTING
//            if (!string.IsNullOrEmpty(sortColumn))
//            {
//                switch (sortColumn)
//                {
//                    case "Id":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Id).ToList()
//                            : list.OrderByDescending(s => s.Id).ToList();
//                        break;
//                    case "Name":
//                        list = isAsc
//                            ? list.OrderBy(s => s.Name).ToList()
//                            : list.OrderByDescending(s => s.Name).ToList();
//                        break;
//                }
//            }
//
//            return list;
//        }
    }
}

projeto.pedido/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Projeto Pedido</title>

    <script src="~/js/variables.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/js/datatables/dataTables.bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Order" asp-action="Table" class="navbar-brand">Projeto Pedido</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-area="" asp-controller="Order" asp-action="Table">Pedidos</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Client" asp-action="Table">Clientes</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Product" asp-action="Table">Produtos</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2018 - Projeto Pedido</p>
    </footer>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/js/datatables/js/jquery.dataTables.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>


@RenderSection("Scripts", required: false)

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"> </script>
</body>
</html>